# Generated by Django 6.0.6 on 2026-07-11 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('cnic', models.CharField(max_length=50)),
                ('address', models.TextField(blank=True, null=True)),
                ('designation', models.CharField(max_length=100)),
                ('dateofjoining', models.DateField()),
                ('employmenttype', models.CharField(choices=[('fulltime', 'Full-time'), ('parttime', 'Part-time'), ('contract', 'Contract')], max_length=20)),
                ('basicsalary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salarytype', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('daily', 'Daily'), ('perjob', 'Per-job')], max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
