# Generated by Django 6.0.6 on 2026-08-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_backend', '0002_businesssettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='backup_directory',
            field=models.CharField(blank=True, default='C:/ERP_Backups', help_text='Local directory path for automated database backups', max_length=500, null=True),
        ),
    ]
