# Generated by Django 6.0.6 on 2026-08-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_backend', '0004_backupsetting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupsetting',
            name='backup_frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('NEVER', 'Never')], default='DAILY', max_length=20),
        ),
    ]
