# Generated by Django 6.0.6 on 2026-08-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_backend', '0005_alter_backupsetting_backup_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesssettings',
            name='address',
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='salary_calculation_basis',
            field=models.CharField(choices=[('working_days', 'Working Days (Excluding Off Days)'), ('fixed_30', 'Fixed 30 Days'), ('month_days', 'Total Calendar Days in Month')], default='working_days', max_length=30),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='weekly_off_days',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
