# Generated by Django 6.0.6 on 2026-08-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_backend', '0006_remove_businesssettings_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
