# Generated by Django 6.0.6 on 2026-08-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_backend', '0007_businesssettings_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssettings',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
