# Generated by Django 6.0.6 on 2026-08-18 15:22

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='current_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='half_unpaid_days',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='leave_unpaid_days',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='month_days',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_paid', 'Half Day (Paid)'), ('half_unpaid', 'Half Day (Unpaid)'), ('leave_paid', 'Leave (Paid)'), ('leave_unpaid', 'Leave (Unpaid)')], db_index=True, max_length=20),
        ),
    ]
