# Generated by Django 6.0.6 on 2026-08-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_attendance_created_at_employeesalary_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_employee_date',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_paid', 'Half Day (Paid)'), ('half_unpaid', 'Half Day (Unpaid)'), ('leave_paid', 'Leave (Paid)'), ('leave_unpaid', 'Leave (Unpaid)'), ('weekly_off', 'Weekly Off')], db_index=True, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
    ]
