# Generated by Django 6.0.6 on 2026-07-13 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_vendor_upgrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='is_deleted',
        ),
    ]
