# Generated by Django 6.0.6 on 2026-07-13 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_remove_purchaseinvoice_total_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='opening_credit',
            new_name='opening_payable',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='credit_balance',
            new_name='payable_balance',
        ),
    ]
