# Generated by Django 6.0.6 on 2026-07-28 12:05

from decimal import Decimal
from django.db import migrations, models

def reset_purchase_discounts(apps, schema_editor):
    PurchaseInvoice = apps.get_model('purchase', 'PurchaseInvoice')
    PurchaseItem = apps.get_model('purchase', 'PurchaseItem')
    PurchaseInvoice.objects.update(invoice_discount=0.0)
    PurchaseItem.objects.update(discount=0.0)

class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_expense_paid_by_expense_person_supplier_expenseitem'),
    ]

    operations = [
        migrations.RunPython(reset_purchase_discounts),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage (0-100)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage (0-100)', max_digits=12),
        ),
    ]
