# Generated by Django 6.0.6 on 2026-08-14 07:41

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('purchase_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sale_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('opening_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('min_stock', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('stock_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_type', models.CharField(default='manual', max_length=50)),
                ('reference_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.item')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
