# Generated by Django 6.0.6 on 2026-08-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salesreturn_salesreturnitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturn',
            name='refund_type',
            field=models.CharField(choices=[('STORE_CREDIT', 'Store Credit / Customer Balance'), ('CASH', 'Cash Refund Paid at Counter')], default='STORE_CREDIT', max_length=20),
        ),
    ]
