# Generated by Django 6.0.6 on 2026-06-26 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], default='Credit', max_length=10),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='walk_in_customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='sales.customer'),
        ),
    ]
