# Generated by Django 6.0.6 on 2026-08-19 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0004_alter_customer_advance_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='item_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_items', to='inventory.item'),
        ),
    ]
