# Generated by Django 6.0.6 on 2026-06-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salesinvoice_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesitem',
            old_name='product_name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='salesitem',
            old_name='sale_price',
            new_name='rate',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='customer',
            name='advance_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='invoice_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='payment_term',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit', 'Credit')], default='Credit', max_length=10),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Saved', 'Saved')], default='Draft', max_length=10),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='units',
            field=models.CharField(default='pcs', max_length=50),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
