# Generated by Django 6.0.6 on 2026-08-21 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0005_salesitem_item_code_salesitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotationitem',
            old_name='item_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='quotationitem',
            old_name='rate',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='unit',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='item',
            field=models.ForeignKey(blank=True, db_column='item_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.item'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='item_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='units',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
