# Generated by Django 6.0.6 on 2026-07-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_paymentreceived'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceived',
            name='applied_to_advance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='paymentreceived',
            name='applied_to_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='paymentreceived',
            name='applied_to_invoice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
