# Generated by Django 6.0.6 on 2026-07-03 11:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_paymentreceived_applied_to_advance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
