# Generated by Django 6.0.6 on 2026-07-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_salesinvoice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='advance_applied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
