# Generated by Django 6.0.6 on 2026-07-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_salesinvoice_advance_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreceived',
            name='method',
            field=models.CharField(default='Cash', max_length=50),
        ),
    ]
