# Generated by Django 6.0.6 on 2026-07-07 10:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_alter_salesinvoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
