# Generated by Django 6.0.6 on 2026-07-28 12:05

from django.db import migrations, models

def reset_sales_discounts(apps, schema_editor):
    SalesInvoice = apps.get_model('sales', 'SalesInvoice')
    SalesItem = apps.get_model('sales', 'SalesItem')
    SalesInvoice.objects.update(invoice_discount=0.0)
    SalesItem.objects.update(discount=0.0)

class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_alter_salesinvoice_date'),
    ]

    operations = [
        migrations.RunPython(reset_sales_discounts),
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage (0-100)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage (0-100)', max_digits=12),
        ),
    ]
