# Generated by Django 6.0.6 on 2026-07-31 09:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_discount_percentages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quotation_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('customer_data', models.JSONField(help_text='Stored exactly as received (customer_name, phone, etc.)')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('valid_days', models.PositiveIntegerField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('payment_term', models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit')], default='cash', max_length=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('converted', 'Converted')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='sales.salesinvoice')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('unit', models.CharField(default='pcs', max_length=50)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage (0-100)', max_digits=12)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.quotation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
